from __future__ import annotations


VISUAL_PROTOTYPE_HTML = r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Options ROI Visual Prototype</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.9/dist/chart.umd.min.js"></script>
  <script src="https://unpkg.com/lucide@0.468.0/dist/umd/lucide.min.js"></script>
  <style>
    :root{
      color-scheme:dark;
      --bg:#081011;--surface:#101a1c;--surface-2:#0c1517;--line:#26373a;
      --text:#eef5f2;--muted:#9eaeaa;--teal:#48cfc0;--green:#78dc90;
      --amber:#f2bd58;--red:#ff6f7e;--blue:#78a8ff;--white:#fff;
    }
    *{box-sizing:border-box}
    [hidden]{display:none!important}
    body{margin:0;background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:14px;letter-spacing:0}
    button,select{font:inherit}
    button{cursor:pointer}
    .shell{max-width:1500px;margin:0 auto;padding:0 20px 48px}
    .topbar{position:sticky;top:0;z-index:20;background:rgba(8,16,17,.96);border-bottom:1px solid var(--line);backdrop-filter:blur(12px)}
    .topbar-inner{max-width:1500px;margin:0 auto;padding:10px 20px;display:flex;align-items:center;gap:18px;min-height:62px}
    .brand{display:flex;align-items:center;gap:10px;min-width:205px}.brand-mark{width:30px;height:30px;border:1px solid var(--teal);display:grid;place-items:center;color:var(--teal);border-radius:6px}.brand strong{font-size:17px}.brand small{display:block;color:var(--muted);margin-top:1px}
    .tabs{display:flex;gap:4px;overflow:auto;scrollbar-width:none}.tabs button{border:0;background:transparent;color:var(--muted);padding:10px 12px;border-radius:6px;white-space:nowrap;font-weight:650}.tabs button.active{background:#17302f;color:var(--text)}
    .top-actions{margin-left:auto;display:flex;gap:8px}.icon-btn{width:38px;height:38px;border:1px solid var(--line);background:var(--surface);color:var(--text);border-radius:6px;display:grid;place-items:center}.icon-btn:hover{border-color:var(--teal)}
    .hero{padding:28px 0 18px;display:flex;justify-content:space-between;gap:20px;align-items:end}.hero h1{margin:0;font-size:30px}.hero-meta{color:var(--muted);text-align:right;line-height:1.5}
    .status-band{display:grid;grid-template-columns:minmax(260px,1.6fr) repeat(3,minmax(130px,.7fr));border:1px solid var(--line);background:var(--surface);border-radius:7px;margin-bottom:20px;overflow:hidden}.status-cell{padding:14px 16px;border-right:1px solid var(--line);min-width:0}.status-cell:last-child{border-right:0}.eyebrow{color:var(--muted);font-size:11px;text-transform:uppercase;font-weight:750}.status-value{font-size:17px;font-weight:750;margin-top:5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.status-detail{color:var(--muted);font-size:12px;margin-top:3px}
    .view{display:none}.view.active{display:block}
    .section-title{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:26px 0 12px}.section-title h2{margin:0;font-size:21px}.section-title .right{color:var(--muted)}
    .grid{display:grid;gap:12px}.two{grid-template-columns:minmax(0,1.25fr) minmax(340px,.75fr)}.two-even{grid-template-columns:repeat(2,minmax(0,1fr))}.three{grid-template-columns:repeat(3,minmax(0,1fr))}
    .panel{background:var(--surface);border:1px solid var(--line);border-radius:7px;min-width:0;overflow:hidden}.panel-head{display:flex;align-items:center;justify-content:space-between;padding:13px 15px;border-bottom:1px solid var(--line)}.panel-head h3{margin:0;font-size:15px}.panel-body{padding:14px 15px}
    .cycle-grid{display:grid;grid-template-columns:minmax(0,1.3fr) repeat(3,minmax(105px,.55fr));gap:10px}.cycle-main{grid-row:span 2}.metric{background:var(--surface-2);border:1px solid #19282a;border-radius:6px;padding:12px;min-height:82px}.metric strong{display:block;font-size:22px;margin-top:7px}.metric small{color:var(--muted);display:block;margin-top:4px}.metric.blue strong{color:var(--blue)}.metric.green strong{color:var(--green)}.metric.amber strong{color:var(--amber)}.metric.red strong{color:var(--red)}
    .cycle-row{display:grid;grid-template-columns:170px minmax(80px,1fr) 92px;gap:12px;align-items:center;margin:11px 0}.cycle-row strong{font-size:13px}.track{height:11px;background:#1d2b2e;border-radius:3px;overflow:hidden}.fill{height:100%;background:var(--green)}.fill.blue{background:var(--blue)}.fill.amber{background:var(--amber)}.fill.red{background:var(--red)}.money{text-align:right;font-variant-numeric:tabular-nums;font-weight:700}
    .group-tabs{display:flex;gap:6px}.group-tabs button{border:1px solid var(--line);background:transparent;color:var(--muted);padding:7px 10px;border-radius:5px;font-weight:650}.group-tabs button.active{border-color:var(--teal);color:var(--text);background:#14302f}
    .action-list{display:grid}.action-row{display:grid;grid-template-columns:72px 120px minmax(180px,1.25fr) minmax(180px,1fr) 90px 90px;gap:12px;align-items:center;padding:12px 14px;border-bottom:1px solid var(--line);cursor:pointer}.action-row:last-child{border-bottom:0}.action-row:hover,.action-row.selected{background:#132124}.ticker{font-size:16px;font-weight:800}.category{font-weight:700}.sub{color:var(--muted);font-size:12px;margin-top:3px}.tag{display:inline-flex;align-items:center;justify-content:center;border-radius:4px;padding:4px 7px;font-size:11px;font-weight:750;background:#203034;color:var(--muted)}.tag.now{background:#48262b;color:#ffc4ca}.tag.plan{background:#40341e;color:#ffd887}.tag.monitor{background:#1e3045;color:#c8dcff}.num{text-align:right;font-variant-numeric:tabular-nums}.pos{color:var(--green)}.neg{color:var(--red)}.warn{color:var(--amber)}.blue{color:var(--blue)}
    .candidate-empty{padding:28px 18px;color:var(--muted);text-align:center}.candidate-state{display:flex;gap:18px;flex-wrap:wrap;padding:12px 14px;border-bottom:1px solid var(--line);background:var(--surface-2)}.candidate-state div{min-width:90px}.candidate-state strong{display:block;margin-top:3px}.candidate-table{width:100%;border-collapse:collapse}.candidate-table th,.candidate-table td{padding:10px 12px;border-bottom:1px solid var(--line);text-align:right;white-space:nowrap}.candidate-table th:first-child,.candidate-table td:first-child{text-align:left}.candidate-table th{color:var(--muted);font-size:10px;text-transform:uppercase}.candidate-table tr:last-child td{border-bottom:0}.candidate-table tr.current{background:#132326}.choice{font-weight:750}.candidate-reason{white-space:normal!important;min-width:210px;text-align:left!important;color:var(--muted)}
    .chart-wrap{height:340px;padding:12px}.chart-wrap.short{height:290px}.legend-row{display:flex;flex-wrap:wrap;gap:14px;color:var(--muted);font-size:12px}.legend-key{display:flex;align-items:center;gap:6px}.dot{width:9px;height:9px;border-radius:50%}
    .recovery-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.recovery-item{background:var(--surface-2);border:1px solid #19282a;border-radius:5px;padding:10px}.recovery-item .ticker{font-size:14px}.recovery-item .bar{height:5px;background:#203034;margin:8px 0}.recovery-item .bar span{display:block;height:100%;background:var(--teal)}
    .heatmap{display:grid;grid-template-columns:repeat(12,minmax(55px,1fr));gap:5px;overflow:auto}.heat-cell{min-height:68px;border:1px solid var(--line);border-radius:5px;padding:8px;display:flex;flex-direction:column;justify-content:space-between}.heat-cell.red{background:#3b2026}.heat-cell.amber{background:#3a311e}.heat-cell.green{background:#173426}.heat-cell.blue{background:#1d3150}.heat-cell .month{font-size:11px;color:#d6dfdc}.heat-cell strong{font-size:16px}
    .assignment-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.assignment-kpis .metric{min-height:92px}
    .loading,.error{min-height:420px;display:grid;place-items:center;color:var(--muted)}.spinner{width:30px;height:30px;border:3px solid var(--line);border-top-color:var(--teal);border-radius:50%;animation:spin .8s linear infinite;margin:0 auto 12px}@keyframes spin{to{transform:rotate(360deg)}}
    .mobile-label{display:none}
    @media(max-width:1050px){.two,.two-even{grid-template-columns:1fr}.status-band{grid-template-columns:repeat(2,1fr)}.status-cell:nth-child(2){border-right:0}.status-cell:nth-child(-n+2){border-bottom:1px solid var(--line)}.cycle-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.cycle-main{grid-column:1/-1;grid-row:auto}.action-row{grid-template-columns:62px 95px minmax(160px,1fr) 80px 80px}.action-row .recommendation{display:none}.assignment-kpis{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:720px){.shell{padding:0 12px 32px}.topbar-inner{padding:8px 12px;gap:8px}.brand{min-width:auto}.brand-text{display:none}.tabs{order:2}.tabs button{padding:9px}.hero{padding-top:20px;align-items:start}.hero h1{font-size:24px}.hero-meta{font-size:11px}.status-band{grid-template-columns:1fr}.status-cell{border-right:0;border-bottom:1px solid var(--line)!important}.status-cell:last-child{border-bottom:0!important}.cycle-grid{grid-template-columns:1fr 1fr}.cycle-row{grid-template-columns:135px 1fr 78px;gap:7px}.action-row{grid-template-columns:52px 1fr 76px;padding:11px 10px}.action-row .category-wrap{min-width:0}.action-row .objective,.action-row .recommendation{display:none}.action-row .num:last-child{display:none}.group-tabs{overflow:auto}.candidate-table,.candidate-table tbody,.candidate-table tr,.candidate-table td{display:block}.candidate-table thead{display:none}.candidate-table tr{padding:10px;border-bottom:1px solid var(--line)}.candidate-table td{border:0;padding:4px 0;text-align:left!important;white-space:normal}.candidate-table td::before{content:attr(data-label);display:inline-block;color:var(--muted);width:46%;font-size:11px;text-transform:uppercase}.chart-wrap{height:300px}.heatmap{grid-template-columns:repeat(6,minmax(74px,1fr))}.assignment-kpis{grid-template-columns:1fr 1fr}.recovery-summary{grid-template-columns:1fr 1fr}}
  </style>
</head>
<body>
  <header class="topbar"><div class="topbar-inner">
    <div class="brand"><div class="brand-mark"><i data-lucide="chart-no-axes-combined"></i></div><div class="brand-text"><strong>Options ROI</strong><small>Visual prototype</small></div></div>
    <nav class="tabs" id="tabs">
      <button class="active" data-view="decisions">Decisions</button><button data-view="risk">Risk</button><button data-view="recovery">Recovery</button><button data-view="performance">Performance</button><button data-view="assignments">Assignments</button>
    </nav>
    <div class="top-actions"><button class="icon-btn" id="reload" title="Reload current data"><i data-lucide="refresh-cw"></i></button></div>
  </div></header>
  <main class="shell">
    <div id="loading" class="loading"><div><div class="spinner"></div><strong>Loading current portfolio</strong></div></div>
    <div id="error" class="error" hidden></div>
    <div id="app" hidden>
      <div class="hero"><div><h1>Decision View</h1></div><div class="hero-meta" id="heroMeta"></div></div>
      <div class="status-band" id="statusBand"></div>

      <section class="view active" data-view="decisions">
        <div id="cycle"></div>
        <div class="section-title"><h2>Action Queue</h2><div class="group-tabs" id="actionTabs"><button class="active" data-group="now">Now</button><button data-group="plan">Plan</button><button data-group="monitor">Monitor</button></div></div>
        <div class="grid two">
          <div class="panel"><div class="action-list" id="actions"></div></div>
          <div class="panel" id="candidatePanel"></div>
        </div>
      </section>

      <section class="view" data-view="risk">
        <div class="section-title"><h2>Open Option Risk</h2><div class="legend-row"><span class="legend-key"><i class="dot" style="background:var(--red)"></i>ITM</span><span class="legend-key"><i class="dot" style="background:var(--amber)"></i>Near strike</span><span class="legend-key"><i class="dot" style="background:var(--blue)"></i>OTM</span></div></div>
        <div class="grid two-even"><div class="panel"><div class="panel-head"><h3>Puts: moneyness vs DTE</h3></div><div class="chart-wrap"><canvas id="putRisk"></canvas></div></div><div class="panel"><div class="panel-head"><h3>Calls: moneyness vs DTE</h3></div><div class="chart-wrap"><canvas id="callRisk"></canvas></div></div></div>
        <div class="section-title"><h2>Exposure by Expiry</h2></div><div class="panel"><div class="chart-wrap short"><canvas id="expiryChart"></canvas></div></div>
      </section>

      <section class="view" data-view="recovery">
        <div class="section-title"><h2>Assigned Holding Recovery</h2><div class="legend-row"><span class="legend-key"><i class="dot" style="background:var(--red)"></i>Uncovered</span><span class="legend-key"><i class="dot" style="background:var(--amber)"></i>Capped</span><span class="legend-key"><i class="dot" style="background:var(--teal)"></i>Covered</span></div></div>
        <div class="panel"><div class="chart-wrap"><canvas id="recoveryChart"></canvas></div></div>
        <div class="section-title"><h2>Recovery Detail</h2></div><div class="recovery-summary" id="recoverySummary"></div>
      </section>

      <section class="view" data-view="performance">
        <div class="section-title"><h2>Performance Composition</h2></div>
        <div class="panel"><div class="chart-wrap"><canvas id="yearlyChart"></canvas></div></div>
        <div class="section-title"><h2>Monthly RoAC</h2><div class="legend-row"><span class="legend-key"><i class="dot" style="background:var(--red)"></i>Negative</span><span class="legend-key"><i class="dot" style="background:var(--amber)"></i>Below band</span><span class="legend-key"><i class="dot" style="background:var(--green)"></i>In band</span><span class="legend-key"><i class="dot" style="background:var(--blue)"></i>Above target</span></div></div>
        <div class="heatmap" id="heatmap"></div>
      </section>

      <section class="view" data-view="assignments">
        <div class="section-title"><h2>Assignment Outcomes</h2></div>
        <div class="assignment-kpis" id="assignmentKpis"></div>
        <div class="grid two-even" style="margin-top:12px"><div class="panel"><div class="panel-head"><h3>Wheel advantage by ticker</h3></div><div class="chart-wrap"><canvas id="assignmentChart"></canvas></div></div><div class="panel"><div class="panel-head"><h3>Outcome by assignment cohort</h3></div><div class="chart-wrap"><canvas id="cohortChart"></canvas></div></div></div>
      </section>
    </div>
  </main>
<script>
const $=id=>document.getElementById(id); let data=null; let actionGroup="now"; let selectedTicker=null; let charts=[];
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const money=v=>{const n=num(v);return n===null?"n/a":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n)};
const pct=v=>{const n=num(v);return n===null?"n/a":`${n>=0?"":""}${n.toFixed(1)}%`};
const pctRatio=v=>{const n=num(v);return n===null?"n/a":`${(n*100).toFixed(1)}%`};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const cls=v=>num(v)===null?"":num(v)<0?"neg":num(v)>0?"pos":"";
const ageDays=iso=>{if(!iso)return null;const ms=Date.now()-new Date(iso).getTime();return Math.max(0,Math.floor(ms/86400000))};
function toneForRatio(v){const n=num(v),floor=num(data.target_floor)||0,target=num(data.target_return)||0;if(n===null)return"";if(n<0)return"red";if(n<floor)return"amber";if(n<=target)return"green";return"blue"}
function metric(label,value,note,tone=""){return `<div class="metric ${tone}"><span class="eyebrow">${esc(label)}</span><strong>${value}</strong><small>${esc(note||"")}</small></div>`}
function status(){
  const s=data.option_status||{}, age=ageDays(s.last_fetched_at), freshTone=age===null?"red":age>7?"red":age>2?"amber":"green";
  $("heroMeta").innerHTML=`Portfolio as of ${esc(data.as_of||"n/a")}<br>Prices ${esc((data.prices_updated_at||"").replace("T"," ").slice(0,19)||"n/a")}`;
  const counts={now:data.actions.filter(x=>x.group==="now").length,plan:data.actions.filter(x=>x.group==="plan").length,monitor:data.actions.filter(x=>x.group==="monitor").length};
  $("statusBand").innerHTML=`<div class="status-cell"><div class="eyebrow">Option data</div><div class="status-value ${freshTone}">${age===null?"Unavailable":`${age} day${age===1?"":"s"} old`}</div><div class="status-detail">${esc(s.provider||"n/a")} · ${Number(s.contract_count||0).toLocaleString()} contracts · ${esc(s.source||"unknown")}</div></div><div class="status-cell"><div class="eyebrow">Act now</div><div class="status-value ${counts.now?"warn":"pos"}">${counts.now}</div><div class="status-detail">time-sensitive situations</div></div><div class="status-cell"><div class="eyebrow">Plan</div><div class="status-value">${counts.plan}</div><div class="status-detail">upcoming decisions</div></div><div class="status-cell"><div class="eyebrow">Monitor</div><div class="status-value">${counts.monitor}</div><div class="status-detail">no immediate action</div></div>`;
}
function cycle(){const c=data.active_cycle||{},max=Math.max(...[c.realized_cycle_pnl,c.open_premium_collected,c.itm_call_stock_pnl,c.itm_put_unrealized_loss,c.projected_cycle_pnl,c.target_pnl].map(v=>Math.abs(num(v)||0)),1),roac=num(c.projected_return_roac),tone=toneForRatio(roac);const rows=[["Realized cycle P&L",c.realized_cycle_pnl],["Open premium collected",c.open_premium_collected],["ITM call stock P&L",c.itm_call_stock_pnl],["ITM put assignment P&L",c.itm_put_unrealized_loss],["Projected cycle P&L",c.projected_cycle_pnl],["Target P&L",c.target_pnl]];$("cycle").innerHTML=`<div class="section-title"><h2>Active Cycle</h2><div class="right">${esc(c.cycle_label||"")}</div></div><div class="cycle-grid"><div class="panel cycle-main"><div class="panel-head"><h3>${esc(c.cycle_label||"Active cycle")}</h3><span class="sub">${(c.open_ticker_count||0)} tickers · DTE ${esc(c.min_dte)}-${esc(c.max_dte)}</span></div><div class="panel-body">${rows.map(([l,v])=>`<div class="cycle-row"><strong>${l}</strong><div class="track"><div class="fill ${l.includes("Projected")?tone:num(v)<0?"red":""}" style="width:${Math.max(4,Math.abs(num(v)||0)/max*100)}%"></div></div><span class="money ${l.includes("Projected")?tone:cls(v)}">${money(v)}</span></div>`).join("")}</div></div>${metric("Projected RoAC",pctRatio(roac),`Target ${pctRatio(c.target_return)}`,tone)}${metric("Put exposure",money(c.cycle_put_exposure),`${money(c.cycle_itm_put_exposure)} ITM`,num(c.cycle_itm_put_exposure)>0?"red":"")}${metric("Call upside capped",money(c.covered_call_upside_foregone),"current cycle",num(c.covered_call_upside_foregone)<0?"amber":"")}${metric("Remaining",money(c.remaining_to_target),"to cycle target",num(c.remaining_to_target)>0?"amber":"blue")}</div>`}
function actionRows(){const rows=data.actions.filter(x=>x.group===actionGroup);if(!selectedTicker||!rows.some(x=>x.ticker===selectedTicker))selectedTicker=rows[0]?.ticker||data.candidate_groups.find(x=>x.candidates.length)?.ticker||null;$("actions").innerHTML=rows.length?rows.map(r=>`<div class="action-row ${r.ticker===selectedTicker?"selected":""}" data-ticker="${esc(r.ticker)}"><span class="tag ${r.group}">${r.group}</span><div><span class="ticker">${esc(r.ticker)}</span><div class="sub">${r.dte==null?"No expiry":`${r.dte} DTE`}</div></div><div class="category-wrap"><div class="category">${esc(r.category)}</div><div class="sub">${esc(r.signal_label)} · <span class="${cls(r.signal_value)}">${money(r.signal_value)}</span></div></div><div class="recommendation"><strong>${esc(r.recommendation)}</strong><div class="sub">${esc(r.objective)}</div></div><div class="num"><span class="sub">Total</span><br><strong class="${cls(r.total_pnl)}">${money(r.total_pnl)}</strong></div><div class="num"><span class="sub">Unrealized</span><br><strong class="${cls(r.unrealized_pnl)}">${money(r.unrealized_pnl)}</strong></div></div>`).join(""):`<div class="candidate-empty">No situations in this group.</div>`;document.querySelectorAll(".action-row").forEach(el=>el.onclick=()=>{selectedTicker=el.dataset.ticker;actionRows();candidatePanel()});candidatePanel()}
function candidatePanel(){const g=data.candidate_groups.find(x=>x.ticker===selectedTicker);if(!g){$("candidatePanel").innerHTML=`<div class="candidate-empty">Select a ticker to compare actions.</div>`;return}const s=g.current_state||{},cs=g.candidates||[];$("candidatePanel").innerHTML=`<div class="panel-head"><div><h3>${esc(g.ticker)} · ${esc(g.category)}</h3><div class="sub">${esc(g.objective)}</div></div><span class="tag ${cs.length?"monitor":"plan"}">${cs.length?`${cs.length} choices`:"no candidate"}</span></div><div class="candidate-state"><div><span class="eyebrow">Current</span><strong>${money(s.current_price)}</strong></div><div><span class="eyebrow">Cost basis</span><strong>${money(s.cost_basis)}</strong></div><div><span class="eyebrow">Assigned</span><strong>${Number(s.assigned_shares||0).toLocaleString()} shares</strong></div><div><span class="eyebrow">Ticker total</span><strong class="${cls(s.total_pnl)}">${money(s.total_pnl)}</strong></div></div>${cs.length?`<div style="overflow:auto"><table class="candidate-table"><thead><tr><th>Action</th><th>Strike / expiry</th><th>Net credit</th><th>EV vs current</th><th>Exercise</th><th>Liquidity</th><th>Rationale</th></tr></thead><tbody>${cs.map(c=>`<tr class="${c.is_current?"current":""}"><td data-label="Action" class="choice">${esc(c.action)}</td><td data-label="Contract">${money(c.strike)} · ${esc(c.expiry||"")}<div class="sub">${c.dte??"n/a"} DTE</div></td><td data-label="Net credit" class="${cls(c.net_credit)}">${money(c.net_credit)}</td><td data-label="EV vs current" class="${cls(c.ev_vs_current)}">${money(c.ev_vs_current)}</td><td data-label="Exercise">${c.exercise_probability==null?"n/a":pct(c.exercise_probability*100)}</td><td data-label="Liquidity">${esc(c.liquidity||"n/a")}<div class="sub">${esc(c.tradeability||"")}</div></td><td data-label="Rationale" class="candidate-reason">${esc(c.reason||"")}</td></tr>`).join("")}</tbody></table></div>`:`<div class="candidate-empty">${esc((g.status||{}).message||"No actionable contract found.")}</div>`}`}
function riskColor(v){const n=num(v)||0;return n>0?"#ff6f7e":n>-5?"#f2bd58":"#78a8ff"}
function scatter(id,type){const rows=data.risk_map.filter(x=>x.type===type),maxDte=Math.max(14,...rows.map(r=>num(r.dte)||0))+7;const ctx=$(id);charts.push(new Chart(ctx,{type:"bubble",data:{datasets:[{data:rows.map(r=>({x:r.moneyness,y:r.dte,r:Math.max(5,Math.min(20,Math.sqrt(r.notional)/14)),label:r.ticker,strike:r.strike,notional:r.notional})),backgroundColor:rows.map(r=>riskColor(r.moneyness)),borderColor:"#081011",borderWidth:1}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${c.raw.label} · ${pct(c.raw.x)} · ${c.raw.y} DTE · ${money(c.raw.notional)}`}}},scales:{x:{title:{display:true,text:"Moneyness (positive = ITM)"},grid:{color:"#26373a"}},y:{min:0,max:maxDte,reverse:true,title:{display:true,text:"Days to expiry"},grid:{color:"#26373a"}}}}}))}
function expiry(){const rows=data.expiry_ladder;charts.push(new Chart($("expiryChart"),{type:"bar",data:{labels:rows.map(x=>x.month),datasets:[{label:"Put assignment exposure",data:rows.map(x=>x.put_exposure),backgroundColor:"#78a8ff"},{label:"ITM put exposure",data:rows.map(x=>x.itm_put_exposure),backgroundColor:"#ff6f7e"},{label:"Covered-call notional",data:rows.map(x=>x.call_notional),backgroundColor:"#48cfc0"}]},options:{maintainAspectRatio:false,plugins:{tooltip:{callbacks:{label:c=>`${c.dataset.label}: ${money(c.raw)}`}}},scales:{x:{stacked:true,grid:{display:false}},y:{stacked:true,grid:{color:"#26373a"},ticks:{callback:v=>money(v)}}}}}))}
function recovery(){const colors={uncovered:"#ff6f7e",capped:"#f2bd58",covered:"#48cfc0"},rows=data.recovery_map;charts.push(new Chart($("recoveryChart"),{type:"bubble",data:{datasets:Object.keys(colors).map(status=>({label:status[0].toUpperCase()+status.slice(1),data:rows.filter(x=>x.status===status).map(r=>({x:r.recovery_pct,y:r.age_days||0,r:Math.max(7,Math.min(22,Math.sqrt(r.capital_tied)/8)),label:r.ticker,total:r.total_pnl,capital:r.capital_tied})),backgroundColor:colors[status]}))},options:{maintainAspectRatio:false,plugins:{tooltip:{callbacks:{label:c=>`${c.raw.label} · recovery ${pct(c.raw.x)} · ${c.raw.y} days · total ${money(c.raw.total)}`}}},scales:{x:{title:{display:true,text:"Price recovery vs cost basis"},grid:{color:"#26373a"},ticks:{callback:v=>`${v}%`}},y:{title:{display:true,text:"Days since assignment"},grid:{color:"#26373a"}}}}}));$("recoverySummary").innerHTML=rows.sort((a,b)=>(a.recovery_pct||0)-(b.recovery_pct||0)).map(r=>`<div class="recovery-item"><div><span class="ticker">${esc(r.ticker)}</span><span class="tag ${r.status==="uncovered"?"now":r.status==="capped"?"plan":"monitor"}" style="float:right">${r.status}</span></div><div class="bar"><span style="width:${Math.max(3,Math.min(100,100+(r.recovery_pct||0)))}%"></span></div><div class="sub">${pct(r.recovery_pct)} from cost · ${money(r.capital_tied)} tied</div><strong class="${cls(r.total_pnl)}">${money(r.total_pnl)} lifecycle</strong></div>`).join("")}
function performance(){const y=data.yearly||[];charts.push(new Chart($("yearlyChart"),{type:"bar",data:{labels:y.map(x=>x.year),datasets:[{label:"Options",data:y.map(x=>x.options),backgroundColor:"#48cfc0"},{label:"Stock",data:y.map(x=>x.stock),backgroundColor:"#78a8ff"},{label:"Dividends",data:y.map(x=>x.dividends),backgroundColor:"#f2bd58"}]},options:{maintainAspectRatio:false,scales:{x:{stacked:true,grid:{display:false}},y:{stacked:true,grid:{color:"#26373a"},ticks:{callback:v=>money(v)}}}}}));const months=(data.monthly||[]).slice(-24);$("heatmap").innerHTML=months.map(m=>{const r=num(m.projected_roac)??num(m.roac),tone=toneForRatio(r);return `<div class="heat-cell ${tone}"><span class="month">${new Date(`${m.month}T00:00:00`).toLocaleDateString("en-US",{month:"short",year:"2-digit"})}</span><strong>${pctRatio(r)}</strong><span class="sub">${money(m.projected??m.realized)}</span></div>`}).join("")}
function assignments(){const a=data.assignment_quality||{},s=a.summary||{},adv=num(s.delta_actual_minus_hold);$("assignmentKpis").innerHTML=metric("Actual path",money(s.actual_total_pnl),"wheel lifecycle","green")+metric("Hold path",money(s.counterfactual_total_pnl),"assignment-and-hold","blue")+metric("Wheel advantage",money(adv),"actual minus hold",adv<0?"red":"green")+metric("Win rate",pctRatio(s.actual_beat_hold_rate),`${s.complete_lots||s.lots||0} complete assignments`);const ticker=a.by_ticker||[];charts.push(new Chart($("assignmentChart"),{type:"bar",data:{labels:ticker.slice(0,16).map(x=>x.ticker),datasets:[{label:"Wheel advantage",data:ticker.slice(0,16).map(x=>num(x.delta_actual_minus_hold)||0),backgroundColor:ticker.slice(0,16).map(x=>(num(x.delta_actual_minus_hold)||0)>=0?"#78dc90":"#ff6f7e")}]},options:{indexAxis:"y",maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{color:"#26373a"},ticks:{callback:v=>money(v)}},y:{grid:{display:false}}}}}));const cohorts=a.by_assignment_year||[];charts.push(new Chart($("cohortChart"),{type:"bar",data:{labels:cohorts.map(x=>x.assignment_year),datasets:[{label:"Actual",data:cohorts.map(x=>num(x.actual_total_pnl)||0),backgroundColor:"#48cfc0"},{label:"Hold",data:cohorts.map(x=>num(x.counterfactual_total_pnl)||0),backgroundColor:"#78a8ff"}]},options:{maintainAspectRatio:false,scales:{x:{grid:{display:false}},y:{grid:{color:"#26373a"},ticks:{callback:v=>money(v)}}}}}))}
function renderCharts(){charts.forEach(c=>c.destroy());charts=[];scatter("putRisk","Put");scatter("callRisk","Call");expiry();recovery();performance();assignments()}
function bind(){document.querySelectorAll("#tabs button").forEach(btn=>btn.onclick=()=>{document.querySelectorAll("#tabs button").forEach(x=>x.classList.toggle("active",x===btn));document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.dataset.view===btn.dataset.view));setTimeout(()=>charts.forEach(c=>c.resize()),0)});document.querySelectorAll("#actionTabs button").forEach(btn=>btn.onclick=()=>{actionGroup=btn.dataset.group;document.querySelectorAll("#actionTabs button").forEach(x=>x.classList.toggle("active",x===btn));actionRows()});$("reload").onclick=load}
async function load(){
  $("loading").hidden=false;$("app").hidden=true;$("error").hidden=true;
  try{const response=await window.fetch(`/api/prototype?ts=${Date.now()}`);if(!response.ok)throw new Error(`${response.status} ${await response.text()}`);data=await response.json();status();cycle();actionRows();renderCharts();bind();if(window.lucide)window.lucide.createIcons();$("app").hidden=false}
  catch(err){$("error").hidden=false;$("error").innerHTML=`<div><strong>Prototype data could not load</strong><div class="sub" style="margin-top:8px">${esc(err.message)}</div></div>`}
  finally{$("loading").hidden=true}
}
load();
</script>
</body></html>'''
